---
title: "Disease Rates"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width = 10, fig.height = 50, fig.path = 'figs/', echo = FALSE, warning = FALSE)
```

```{r load_data}
library(reshape2)
library(ggplot2)

datafile <- "data/prevalence.RData"
 if (file.exists(datafile)) {
  load(datafile)
 } else {
  source("code/getfiles_breastcancer.R")
  source("code/getfiles_HIV.R")
  source("code/poverty.R")
 }

melted <- melt(town.rates[, c(1, 2, 4, 6)], id.vars = "town")
melted$town <- factor(melted$town)
melted$town <- factor(melted$town, levels = rev(levels(melted$town)), ordered = TRUE)

plots <- function(z) {
  ggplot(z, aes(x = town, y = value, fill = value, label = round(value, 0))) + 
    geom_bar(stat = "identity") + 
    coord_flip() +
    guides(fill = FALSE) +
    geom_text(size = 3.5, hjust = -0.3) +
    ylab("rate") +
    theme(axis.text = element_text(colour = "black"))
}
```

### Breast Cancer

Incident Rate per 100,000 People

Source: http://www.mass.gov/eohhs/researcher/community-health/masschip/breast-cancer.html

```{r breast_cancer}
plots(melted[melted$variable == "breast.cancer.rate", ])
```

### HIV/AIDS

Prevalence Rate per 100,000 People

Source: http://www.mass.gov/eohhs/researcher/community-health/masschip/health-status-indicators.html

```{r hiv}
plots(melted[melted$variable == "HIV.rate", ])
```

### Poverty

Percent Below Federal Poverty Level

Source: http://factfinder.census.gov/bkmk/table/1.0/en/ACS/13_5YR/GCT1701.US13PR/0100000US

```{r poverty}
plots(melted[melted$variable == "poverty.rate", ])
```
